version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  adminer:
    image: adminer
    restart: always
    ports: 
      - 8080:8080
  server:
    build:
      dockerfile: Dockerfile.dev
      context: './server'
    volumes:
      - /app/nodes_modules 
      - ./server:/app
    ports:
      - "3001:3001"
  client: 
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: './client'
    volumes:
      - /app/nodes_modules
      - ./client:/app
    ports:
      - 3000:3000