version: '3.9'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: matcha
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  adminer:
    image: adminer
    restart: always
    ports: 
      - '8080:8080'
  server:
    build:
      dockerfile: Dockerfile.dev
      context: './server'
    volumes:
      - /app/node_modules 
      - ./server:/app
    ports:
      - "3001:3001"
    depends_on:
      - db
    env_file:
      - .env
    restart: on-failure
  client: 
    build:
      dockerfile: Dockerfile.dev
      context: './client'
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - '3000:3000'

networks:
  default:
    name: 'matcha_network'