version: '3.8'

services:
  postgres: 
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
  api:
    build:
      dockerfile: Dockerfile.dev
      context: './server'
    volumes:
      - /app/nodes_modules
      - ./server:/app
    environment:
      - PGUSER=postgres
      - PGHOST=localhost
      - PGDATABASE=matcha
      - PGPASSWORD=postgres
      - PGPORT=5432
    ports:
      - 3001:3001
  client: 
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: './client'
    volumes:
      - /app/nodes_modules
      - ./client:/app
    ports:
      - 3000:3000