version: '3.8'

services:
  script:
    build: ./
    env_file:
      - .env2
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run start

networks:
  default:
    name: matcha_network
    external: true
